name: release
on:
  push:
    branches: ["*"]
    tags: ["*"]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: push
      run: |
        docker login docker.pkg.github.com --username convox --password "${GITHUB_TOKEN}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}